spring:
    profiles:
        active: local
    jpa:
        hibernate:
            #USE ONLY WHEN DB HAS BEEN INITIALIZED
            ddl-auto: update
            
            #USE ONLY WHEN DB NEEDS INITIALIZATION
            # ddl-auto : create
    h2:
        console:
            enabled: true
properties:
    message: testingmessage

---

spring: 
    profiles: cloud
    datasource:
        url: jdbc:mysql://localhost/incentify
        username: root
        password: toor

--- 

spring:
    profiles: local
    datasource:
        url: jdbc:mysql://localhost/incentify
        username: root
        password: toor