spring:
    server:
        port: 8080
    user:
        datasource:
            driver-class-name: com.mysql.jdbc.Driver
    profiles:
        active: local
    jpa:
        show-sql: true
        hibernate:
            #USE ONLY WHEN DB HAS BEEN INITIALIZED
            ddl-auto: update
            
            #USE ONLY WHEN DB NEEDS INITIALIZATION
            # ddl-auto : create
    h2:
        console:
            enabled: true
    spring:
        security:
            username: user
            password: user
---

spring:
    profiles: cloud
    datasource:
        url: jdbc:mysql://localhost:3306/incentify
        username: root
        password: Sergei13

--- 

spring:
    profiles: local
    datasource:
        url: jdbc:mysql://localhost:3306/incentify?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: Sergei13
